<h1>Список сообщений</h1>
<?php /**
 * @var $message \App\Model\Message
 */
?>
<?php if($messages = $this->messages): ?>
    <?php foreach($messages as $message): ?>
        <div>
            <?php if($author = $message->getAuthor()): ?>
                <p class="author"><?= htmlspecialchars($author->getName()); ?></p>
            <?php else: ?>
                <p class="author">Этот пользователь больше не существует</p>
            <?php endif; ?>
            <p class="text"><?= $message->getCreatedAt(); ?> <?= htmlspecialchars(nl2br($message->getTextMessage())); ?></p>
            <?php if($message->getImage()): ?>
                <div><img src="/images/<?= $message->getImage(); ?>"</div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <p>Сообщений пока нет</p>
<?php endif; ?>


<p>Добавить сообщение</p>
<form enctype="multipart/form-data" action="blog/addMessage" method="post">
    <div class="form__input">
        <textarea type="text" value="" name="name" placeholder="Введите сообщение"></textarea>
    </div>
    <div class="form__input">
        Загрузите изображение: <input type="file" name="image">
    </div>
    <input type="submit" value="Send">
</form>

<form action="/user/logout">
    <input type="submit" value="Log out">
</form>