<html>
<head>
    <style>
        .block { display: inline-block; vertical-align: top; text-align: left; }
        .block input { width: 150px; }
        .field { width: 150px; display: inline-block; margin-bottom: 5px }
    </style>
</head>
<body>
<h3><?=$this->title;?></h3>
<?php
/** @var \App\Model\User $user */
$user = $this->user;
?>

<? if(!$user): ?>
    <div class="block">
        Регистрация:
        <form action="/user/register" method="post">
            <div class="form__input">
                Login: <input type="text" value="" name="name">
            </div>
            <div class="form__input">
                Email: <input type="text" value="" name="email">
            </div>
            <div class="form__input">
                Password: <input type="text" value="" name="password" pattern="[A-Za-zА-Яа-яЁё-0-9]{4,}">
            </div>
            <input type="submit" value="Register">
        </form>
        <br>
        <br>

        Войти
        <form action="/user/login" method="post">
            <div class="form__input">
                Login: <input type="text" value="" name="name">
            </div>
            <div class="form__input">
                Password: <input type="password" value="" name="password" pattern="[A-Za-zА-Яа-яЁё-0-9]{4,}">
            </div>
            <div class="form__input">
                Confirm password: <input type="password" value="" name="password_2" pattern="[A-Za-zА-Яа-яЁё-0-9]{4,}">
            </div>
            <input type="submit" value="Log in">
        </form>
    </div>
</body>
</head>
</html>