Регистрация:
<form action="/user/register" method="post">
    <div class="form__input">
        Login: <input type="text" value="" name="name">
    </div>
    <div class="form__input">
        Email: <input type="text" value="" name="email">
    </div>
    <div class="form__input">
        Password: <input type="text" value="" name="password" pattern="[A-Za-zА-Яа-яЁё-0-9]{4,}">
    </div>
    <input type="submit" value="Register">
</form>
<br>
<br>

Войти
<form action="/user/login" method="post">
<!--    <div class="form__input">-->
        Login: <input type="text" value="" name="name">
<!--    </div>-->
<!--    <div class="form__input">-->
        Password: <input type="password" value="" name="password" ">
<!--    </div>-->
<!--    <div class="form__input">pattern="[A-Za-zА-Яа-яЁё-0-9]{4,}-->
<!--        Confirm password: <input type="password" value="" name="password_2" pattern="[A-Za-zА-Яа-яЁё-0-9]{4,}">-->
<!--    </div>-->
    <input type="submit" value="Log in">
</form>

<br>
<br>
<?php if($this->error): ?>
    <span style="color: red"><?=$this->error;?></span>
<?php endif; ?>